---
title: "fit full models"
author: "SPT"
date: "2021_08_16"
output: github_document
---

### Step 1: Load packages and data

```{r, setup, include = `FALSE`, echo = `FALSE`}
knitr::opts_knit$set(root.dir = "/Users/simontye/Research/Projects/MME_Temp/2020_MME_Temp")
```

```{r, echo = `FALSE`}
# Load packages
library(tidyverse)
library(rsample)
library(caret)
library(glmnet)
library(Matrix)
library(e1071)
library(pROC)
library(PRROC) 
library(glmnetUtils)
library(doParallel)
library(lme4)
library(dplyr)

# Reset global environment
rm(list = ls())

# Set working directory
setwd("/Users/simontye/Research/Projects/MME_Temp/2020_MME_Temp")

# Load data
df.historical <- read.csv(file = "data/processed/df_historical.csv", head = TRUE, sep = ",")
df.test       <- read.csv(file = "data/processed/df_test.csv", head = TRUE, sep = ",")
training      <- read.csv(file = "data/models/training.csv", head = TRUE, sep = ",")
testing       <- read.csv(file = "data/models/testing.csv",  head = TRUE, sep = ",")
```

### Step 2: Verify formatting

```{r, echo = `FALSE`}
# Format test dataset
df.test <- df.test %>%
  mutate(year         = as.character(year),
         month        = as.character(month),
         season       = as.factor(season),
         summerkill   = as.factor(summerkill),
         lat          = as.numeric(lat),
         long         = as.numeric(long),
         state        = as.factor(state),
         population   = as.numeric(population),
         mean_bot_z   = as.numeric(mean_bot_z),
         mean_surf_z  = as.numeric(mean_surf_z),
         mean_air_z   = as.numeric(mean_air_z),
         ice_duration = as.numeric(ice_duration))

# Format historical dataset
df.historical <- df.historical %>%
  mutate(year         = as.character(year),
         month        = as.character(month),
         season       = as.factor(season),
         summerkill   = as.factor(summerkill),
         lat          = as.numeric(lat),
         long         = as.numeric(long),
         state        = as.factor(state),
         population   = as.numeric(population),
         mean_bot_z   = as.numeric(mean_bot_z),
         mean_surf_z  = as.numeric(mean_surf_z),
         mean_air_z   = as.numeric(mean_air_z),
         ice_duration = as.numeric(ice_duration))

# Scale historical data (df.test = df.historical w/ model variables only)
pre.proc.test <- preProcess(df.test, method = c("center", "scale"))
df.test       <- predict(pre.proc.test, df.test)

# Reformat training data
training <- training %>%
  mutate(year         = as.character(year),
         month        = as.character(month),
         season       = as.factor(season),
         summerkill   = as.factor(summerkill),
         lat          = as.numeric(lat),
         long         = as.numeric(long),
         state        = as.factor(state),
         population   = as.numeric(population),
         mean_bot_z   = as.numeric(mean_bot_z),
         mean_surf_z  = as.numeric(mean_surf_z),
         mean_air_z   = as.numeric(mean_air_z),
         ice_duration = as.numeric(ice_duration))

# Reformat testing data
testing <- testing %>%
  mutate(year         = as.character(year),
         month        = as.character(month),
         season       = as.factor(season),
         summerkill   = as.factor(summerkill),
         lat          = as.numeric(lat),
         long         = as.numeric(long),
         state        = as.factor(state),
         population   = as.numeric(population),
         mean_bot_z   = as.numeric(mean_bot_z),
         mean_surf_z  = as.numeric(mean_surf_z),
         mean_air_z   = as.numeric(mean_air_z),
         ice_duration = as.numeric(ice_duration))

# Calculate R^2 from true and predicted values for ridge and lasso regressions
eval_results <- function(true, predicted, df) {
  SSE <- sum((predicted - true)^2)
  SST <- sum((true - mean(true))^2)
  R_square <- 1 - SSE / SST
  RMSE = sqrt(SSE/nrow(df))

  # Model performance metrics
  data.frame(
    RMSE = RMSE,
    Rsquare = R_square)
}
```

### Step 3: Specify models

Set up simple and complex air and water temperature models for all taxa

```{r, echo = `FALSE`}
# Air model
a1 <- summerkill ~ lat + long + season + population +
   max_air + max_air_z + ice_duration + precip

# Water model
w1 <- summerkill ~ lat + long + season + population +
  mean_surf + mean_surf_z + ice_duration + precip

# No downsampling
control.logloss <- trainControl(method          = "repeatedcv",
                                number          = 5,
                                repeats         = 5,
                                summaryFunction = mnLogLoss,
                                classProbs      = TRUE)

# Downsampling
control.logloss.ds <- trainControl(method          = "repeatedcv",
                                   number          = 5,
                                   repeats         = 5,
                                   summaryFunction = mnLogLoss,
                                   classProbs      = TRUE,
                                   sampling        = "down")
```

### Step 4: Logistic models

```{r, echo = `FALSE`}
# a1
full_logistic_a1_backwards <- glm(a1,
                                  df.test,
                                  family = "binomial")

# w1
full_logistic_w1_backwards <- glm(w1,
                                  df.test,
                                  family = "binomial")

# Backwards selection
full_logistic_a1_backwards <- step(full_logistic_a1_backwards)
full_logistic_w1_backwards <- step(full_logistic_w1_backwards)

# Save model
write_rds(full_logistic_a1_backwards, "data/models/full/full_logistic_a1_backwards.rds")
write_rds(full_logistic_w1_backwards, "data/models/full/full_logistic_w1_backwards.rds")
```

### Step 5: Ridge models

```{r, echo = `FALSE`}
# Create grid of parameters
par_grid <-  expand.grid(alpha = 0, lambda = seq(3.5e-7, 1.5e-5, length.out = 6))

# Set seed
set.seed(538)

# a1 model
full_ridge_a1_ds <- train(a1, 
                          data      = df.test, 
                          method    = "glmnet",
                          metric    = "logLoss",
                          tuneGrid  = par_grid,
                          trControl = control.logloss.ds)

# w1 model
full_ridge_w1_ds <- train(w1, 
                          data      = df.test, 
                          method    = "glmnet",
                          metric    = "logLoss",
                          tuneGrid  = par_grid,
                          trControl = control.logloss.ds)

# Save model
write_rds(full_ridge_a1_ds, "data/models/full/full_ridge_a1_ds.rds")
write_rds(full_ridge_w1_ds, "data/models/full/full_ridge_w1_ds.rds")
```

######################################
Proceed to `06_statistics.Rmd`
######################################
